In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = '../data/processed/merged_df.parquet'

In [3]:
df = pd.read_parquet(data)

In [4]:
df.shape

(1097231, 306)

In [5]:
df.head(30)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_30,id_31,id_32,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,screen_area
0,2987000,0.0,86400,68.500000,W,13926,missing,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0.0,86401,29.000000,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0.0,86469,59.000000,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0.0,86499,50.000000,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0.0,86506,50.000000,H,4497,514.0,150.0,mastercard,102.0,...,android,other_browser,32.0,T,F,T,T,mobile,other_device,2397600.0
5,2987005,0.0,86510,49.000000,W,5937,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2987006,0.0,86522,159.000000,W,12308,360.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2987007,0.0,86529,422.500000,W,12695,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2987008,0.0,86535,15.000000,H,2803,100.0,150.0,visa,226.0,...,apple,safari,32.0,T,F,F,T,mobile,iOS Device,1000500.0
9,2987009,0.0,86536,117.000000,W,17399,111.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2987010,0.0,86549,75.887001,C,16496,352.0,117.0,mastercard,134.0,...,missing,chrome,missing,F,F,T,T,desktop,Windows,-1.0
11,2987011,0.0,86555,16.495001,C,4461,375.0,185.0,mastercard,224.0,...,missing,chrome,missing,F,F,T,T,desktop,missing,-1.0
12,2987012,0.0,86564,50.000000,W,3786,418.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2987013,0.0,86585,40.000000,W,12866,303.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2987014,0.0,86596,10.500000,W,11839,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2987015,0.0,86618,57.950001,W,7055,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2987016,0.0,86620,30.000000,H,1790,555.0,150.0,visa,226.0,...,apple,chrome,24.0,T,F,T,T,desktop,MacOS,1024000.0
17,2987017,0.0,86668,100.000000,H,11492,111.0,150.0,mastercard,219.0,...,windows,chrome,24.0,T,F,T,T,desktop,Windows,1049088.0
18,2987018,0.0,86725,47.950001,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2987019,0.0,86730,186.000000,W,7005,111.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2987020,0.0,86761,39.000000,W,7875,314.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2987021,0.0,86769,159.949997,W,11401,543.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2987022,0.0,86786,50.000000,H,1724,583.0,150.0,visa,226.0,...,missing,missing,missing,missing,missing,missing,missing,missing,missing,-1.0
23,2987023,0.0,86808,107.949997,W,2392,360.0,150.0,mastercard,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2987024,0.0,86821,73.949997,W,10112,360.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2987025,0.0,86944,107.949997,W,15385,111.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2987026,0.0,86945,184.000000,W,17868,148.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2987027,0.0,86972,47.950001,W,11307,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2987028,0.0,86973,20.000000,W,8431,269.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2987029,0.0,86979,36.990002,W,12932,361.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data2 = '../data/processed/df_features.parquet'

In [7]:
df2 = pd.read_parquet(data2)

In [8]:
df2.head(30)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,cum_historical_mean_amt,amt_dev_from_cum_mean,addr1_amt_dev_mean,addr1_amt_dev_median,addr1_amt_zscore,ProductCD_amt_dev_mean,ProductCD_amt_dev_median,ProductCD_amt_zscore,cum_unique_p_emails,cum_unique_devices
0,3169988,0.0,4050851,29.000000,W,10000,111.0,150.0,mastercard,117.0,...,-999.000000,-999.000000,-117.563263,-53.949997,-0.461368,-124.611755,-49.949997,-0.457815,1,0
1,3801080,NaN,23142547,2003.349976,W,10001,555.0,150.0,visa,226.0,...,-999.000000,-999.000000,1851.394897,1915.400024,7.341070,1849.738281,1924.400024,6.795808,1,0
2,4057742,NaN,31721781,226.000000,W,10002,302.0,150.0,visa,226.0,...,-999.000000,-999.000000,95.677200,139.000000,0.548466,72.388245,147.050003,0.265949,1,0
3,3923735,NaN,27438765,51.213001,C,10002,302.0,150.0,visa,226.0,...,-999.000000,-999.000000,9.834332,21.970001,0.222565,9.579903,21.654001,0.240319,1,1
4,3328484,0.0,8421815,39.394001,C,10003,555.0,128.0,visa,226.0,...,-999.000000,-999.000000,-1.984669,10.151001,-0.044916,-2.239098,9.835001,-0.056169,1,1
5,3337343,0.0,8634882,10.755000,C,10003,555.0,128.0,visa,226.0,...,39.394001,-28.639000,-30.623669,-18.487999,-0.693057,-30.878098,-18.804001,-0.774599,2,1
6,3337365,0.0,8635215,19.093000,C,10003,555.0,128.0,visa,226.0,...,25.074501,-5.981501,-22.285669,-10.150000,-0.504356,-22.540098,-10.466000,-0.565434,2,1
7,3337822,0.0,8642405,19.093000,C,10003,555.0,128.0,visa,226.0,...,23.080666,-3.987665,-22.285669,-10.150000,-0.504356,-22.540098,-10.466000,-0.565434,2,2
8,3301550,0.0,7840676,42.777000,C,10003,missing,missing,missing,missing,...,-999.000000,-999.000000,1.398331,13.534000,0.031646,1.143902,13.218000,0.028696,1,1
9,3144103,0.0,3271265,1575.500000,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,1439.498169,1503.500000,6.158201,1421.888184,1496.550049,5.223917,1,0
10,4117380,NaN,33175751,75.000000,R,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-56.499146,7.050003,-0.247471,-104.756027,-53.000000,-0.583061,1,1
11,4144019,NaN,33660175,100.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-31.499146,32.050003,-0.137969,27.113998,50.000000,0.449729,1,1
12,3703462,NaN,19763816,400.000000,R,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,238.557281,303.000000,0.877506,220.243973,272.000000,1.225855,1,1
13,3012474,0.0,663069,50.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-111.442719,-47.000000,-0.409929,-22.886002,0.000000,-0.379601,1,1
14,3325651,0.0,8345697,200.000000,R,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,38.557281,103.000000,0.141829,20.243973,72.000000,0.112676,1,1
15,3051248,0.0,1454318,25.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-104.290405,-42.949997,-0.478431,-47.886002,-25.000000,-0.794265,1,1
16,3082987,0.0,1967267,50.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-79.290405,-17.949997,-0.363744,-22.886002,0.000000,-0.379601,1,1
17,3330322,0.0,8461404,1899.349976,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,1770.059570,1831.400024,8.120131,1745.738281,1820.400024,6.413720,1,0
18,4067035,NaN,31950882,1609.949951,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,1476.627686,1512.000000,8.360511,1456.338135,1531.000000,5.350484,1,0
19,2988962,0.0,141079,72.949997,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-92.670105,-24.050003,-0.339168,-80.661758,-6.000000,-0.296346,1,0
20,3072795,0.0,1811727,30.950001,W,10004,529.0,150.0,visa,162.0,...,72.949997,-41.999996,-134.670105,-66.050003,-0.492886,-122.661758,-47.999996,-0.450651,1,0
21,3679185,NaN,18905741,248.479996,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,82.859894,151.479996,0.303263,94.868240,169.529999,0.348539,1,0
22,3215791,0.0,5424498,664.000000,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,498.379883,567.000000,1.824046,510.388245,585.049988,1.875131,1,0
23,3491083,0.0,13203599,502.600006,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,335.587280,402.600006,1.232419,348.988251,423.650024,1.282158,1,0
24,3711568,NaN,20017494,50.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-117.012741,-50.000000,-0.429721,-22.886002,0.000000,-0.379601,1,1
25,3713370,NaN,20065288,107.000000,H,10004,529.0,150.0,visa,162.0,...,50.000000,57.000000,-60.012741,7.000000,-0.220392,34.113998,57.000000,0.565835,1,1
26,4023694,NaN,30685864,35.000000,H,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,-132.012741,-65.000000,-0.484807,-37.886002,-15.000000,-0.628400,1,1
27,3340776,0.0,8727712,944.950012,W,10004,529.0,150.0,visa,162.0,...,-999.000000,-999.000000,784.365479,857.000000,3.055912,791.338257,866.000000,2.907321,1,0
28,3340871,0.0,8730021,944.950012,W,10004,529.0,150.0,visa,162.0,...,944.950012,0.000000,784.365479,857.000000,3.055912,791.338257,866.000000,2.907321,1,0
29,3695723,NaN,19499042,944.950012,W,10004,529.0,150.0,visa,162.0,...,944.950073,-0.000061,784.365479,857.000000,3.055912,791.338257,866.000000,2.907321,1,0

In [9]:
df2.isna().sum().sort_values(ascending=False).head(60)

id_21                                    811091
id_28                                    811091
id_29                                    811091
id_30                                    811091
id_31                                    811091
id_32                                    811091
id_35                                    811091
id_20                                    811091
id_37                                    811091
id_38                                    811091
DeviceType                               811091
DeviceInfo                               811091
screen_area                              811091
id_02                                    811091
id_01                                    811091
id_03                                    811091
id_36                                    811091
id_05                                    811091
id_06                                    811091
id_09                                    811091
id_11                                    811091
id_12                                    811091
id_13                                    811091
id_14                                    811091
id_15                                    811091
id_16                                    811091
id_18                                    811091
id_04                                    811091
id_19                                    811091
_num_M5_user_id_refined_mean             803547
_num_M8_user_id_refined_mean             711567
_num_M1_user_id_refined_mean             652434
D9_user_id_refined_std                   651870
D15_N_user_id_refined_std                651870
D10_N_user_id_refined_std                651870
D4_N_user_id_refined_std                 651870
_num_M6_user_id_refined_mean             616033
isFraud                                  506691
D10_N_user_id_refined_mean               450360
D4_N_user_id_refined_mean                450360
D15_N_user_id_refined_mean               450360
D9_user_id_refined_mean                  450360
C1_user_id_refined_mean                  450360
C6_user_id_refined_mean                  450360
C2_user_id_refined_mean                  450360
C5_user_id_refined_mean                  450360
ProductCD_user_id_refined_nunique        450360
id_02_user_id_refined_nunique            450360
R_emaildomain_user_id_refined_nunique    450360
P_emaildomain_user_id_refined_nunique    450360
C13_user_id_refined_mean                 450360
C9_user_id_refined_mean                  450360
C12_user_id_refined_mean                 450360
C11_user_id_refined_mean                 450360
C8_user_id_refined_mean                  450360
C7_user_id_refined_mean                  450360
V_pattern_6517030450377495652_PCA_3           0
V_pattern_6517030450377495652_PCA_4           0
V_pattern_6517030450377495652_PCA_5           0
V_pattern_6517030450377495652_PCA_6           0
dtype: int64

In [10]:
pd.set_option('display.max_rows', None)

In [11]:
df2.dtypes

TransactionID                               int32
isFraud                                   float64
TransactionDT                               int32
TransactionAmt                            float32
ProductCD                                category
card1                                         str
card2                                         str
card3                                         str
card4                                    category
card5                                         str
card6                                         str
addr1                                         str
addr2                                         str
dist1                                     float32
dist2                                     float32
P_emaildomain                                 str
R_emaildomain                            category
C1                                        float32
C2                                        float32
C3                                        float32
C5                                        float32
C6                                        float32
C7                                        float32
C8                                        float32
C9                                        float32
C11                                       float32
C12                                       float32
C13                                       float32
D1                                        float32
D2                                        float32
D3                                        float32
D4                                        float32
D5                                        float32
D6                                        float32
D7                                        float32
D8                                        float32
D9                                        float32
D10                                       float32
D11                                       float32
D12                                       float32
D13                                       float32
D14                                       float32
D15                                       float32
M1                                       category
M5                                       category
M6                                       category
M8                                       category
is_test                                      int8
D1_N                                      float32
D1_N_floored                                int16
D2_N                                      float32
D3_N                                      float32
D4_N                                      float32
D5_N                                      float32
D6_N                                      float32
D7_N                                      float32
D8_N                                      float32
D9_N                                      float32
D10_N                                     float32
D11_N                                     float32
D12_N                                     float32
D13_N                                     float32
D14_N                                     float32
D15_N                                     float32
V_pattern_9095697929967337070_PCA_1       float32
V_pattern_9095697929967337070_PCA_2       float32
V_pattern_9095697929967337070_PCA_3       float32
V_pattern_9095697929967337070_PCA_4       float32
V_pattern_9095697929967337070_PCA_5       float32
V_pattern_9095697929967337070_PCA_6       float32
V_pattern_9095697929967337070_PCA_7       float32
V_pattern_9095697929967337070_PCA_8       float32
V_pattern_9095697929967337070_PCA_9       float32
V_pattern_9095697929967337070_PCA_10      float32
V_pattern_9095697929967337070_PCA_11      float32
V_pattern_9095697929967337070_PCA_12      float32
V_pattern_9095697929967337070_PCA_13      float32
V_pattern_9095697929967337070_PCA_14      float32
V_pattern_9095697929967337070_PCA_15      float32
V_pattern_1481343147964654334_PCA_1       float32
V_pattern_1481343147964654334_PCA_2       float32
V_pattern_1481343147964654334_PCA_3       float32
V_pattern_1481343147964654334_PCA_4       float32
V_pattern_1481343147964654334_PCA_5       float32
V_pattern_1481343147964654334_PCA_6       float32
V_pattern_1481343147964654334_PCA_7       float32
V_pattern_1481343147964654334_PCA_8       float32
V_pattern_1481343147964654334_PCA_9       float32
V_pattern_1481343147964654334_PCA_10      float32
V_pattern_1481343147964654334_PCA_11      float32
V_pattern_1471133412241335534_PCA_1       float32
V_pattern_1471133412241335534_PCA_2       float32
V_pattern_1471133412241335534_PCA_3       float32
V_pattern_1471133412241335534_PCA_4       float32
V_pattern_1471133412241335534_PCA_5       float32
V_pattern_1471133412241335534_PCA_6       float32
V_pattern_1471133412241335534_PCA_7       float32
V_pattern_1471133412241335534_PCA_8       float32
V_pattern_1471133412241335534_PCA_9       float32
V_pattern_1471133412241335534_PCA_10      float32
V_pattern_1471133412241335534_PCA_11      float32
V_pattern_1471133412241335534_PCA_12      float32
V_pattern_1471133412241335534_PCA_13      float32
V_pattern_1471133412241335534_PCA_14      float32
V_pattern_1471133412241335534_PCA_15      float32
V_pattern_1419185338251412470_PCA_1       float32
V_pattern_1419185338251412470_PCA_2       float32
V_pattern_1419185338251412470_PCA_3       float32
V_pattern_1419185338251412470_PCA_4       float32
V_pattern_1419185338251412470_PCA_5       float32
V_pattern_1419185338251412470_PCA_6       float32
V_pattern_1419185338251412470_PCA_7       float32
V_pattern_1419185338251412470_PCA_8       float32
V_pattern_1419185338251412470_PCA_9       float32
V_pattern_1419185338251412470_PCA_10      float32
V_pattern_1419185338251412470_PCA_11      float32
V_pattern_1419185338251412470_PCA_12      float32
V_pattern_1419185338251412470_PCA_13      float32
V_pattern_1419185338251412470_PCA_14      float32
V_pattern_1419185338251412470_PCA_15      float32
V_pattern_959003356291144933_PCA_1        float32
V_pattern_959003356291144933_PCA_2        float32
V_pattern_959003356291144933_PCA_3        float32
V_pattern_959003356291144933_PCA_4        float32
V_pattern_959003356291144933_PCA_5        float32
V_pattern_959003356291144933_PCA_6        float32
V_pattern_959003356291144933_PCA_7        float32
V_pattern_959003356291144933_PCA_8        float32
V_pattern_959003356291144933_PCA_9        float32
V_pattern_959003356291144933_PCA_10       float32
V_pattern_959003356291144933_PCA_11       float32
V_pattern_959003356291144933_PCA_12       float32
V_pattern_959003356291144933_PCA_13       float32
V_pattern_959003356291144933_PCA_14       float32
V_pattern_959003356291144933_PCA_15       float32
V_pattern_495946718234339098_PCA_1        float32
V_pattern_495946718234339098_PCA_2        float32
V_pattern_495946718234339098_PCA_3        float32
V_pattern_495946718234339098_PCA_4        float32
V_pattern_495946718234339098_PCA_5        float32
V_pattern_495946718234339098_PCA_6        float32
V_pattern_495946718234339098_PCA_7        float32
V_pattern_495946718234339098_PCA_8        float32
V_pattern_495946718234339098_PCA_9        float32
V_pattern_495946718234339098_PCA_10       float32
V_pattern_495946718234339098_PCA_11       float32
V_pattern_495946718234339098_PCA_12       float32
V_pattern_495946718234339098_PCA_13       float32
V_pattern_495946718234339098_PCA_14       float32
V_pattern_495946718234339098_PCA_15       float32
V_pattern_20371842263915580_PCA_1         float32
V_pattern_20371842263915580_PCA_2         float32
V_pattern_20371842263915580_PCA_3         float32
V_pattern_20371842263915580_PCA_4         float32
V_pattern_20371842263915580_PCA_5         float32
V_pattern_20371842263915580_PCA_6         float32
V_pattern_20371842263915580_PCA_7         float32
V_pattern_20371842263915580_PCA_8         float32
V_pattern_20371842263915580_PCA_9         float32
V_pattern_20371842263915580_PCA_10        float32
V_pattern_20371842263915580_PCA_11        float32
V_pattern_20371842263915580_PCA_12        float32
V_pattern_20371842263915580_PCA_13        float32
V_pattern_20371842263915580_PCA_14        float32
V_pattern_20371842263915580_PCA_15        float32
V_pattern_36380958907524819_PCA_1         float32
V_pattern_36380958907524819_PCA_2         float32
V_pattern_36380958907524819_PCA_3         float32
V_pattern_36380958907524819_PCA_4         float32
V_pattern_36380958907524819_PCA_5         float32
V_pattern_36380958907524819_PCA_6         float32
V_pattern_36380958907524819_PCA_7         float32
V_pattern_36380958907524819_PCA_8         float32
V_pattern_36380958907524819_PCA_9         float32
V_pattern_36380958907524819_PCA_10        float32
V_pattern_36380958907524819_PCA_11        float32
V_pattern_1341337460919381558_PCA_1       float32
V_pattern_1341337460919381558_PCA_2       float32
V_pattern_1341337460919381558_PCA_3       float32
V_pattern_1341337460919381558_PCA_4       float32
V_pattern_1341337460919381558_PCA_5       float32
V_pattern_1341337460919381558_PCA_6       float32
V_pattern_1341337460919381558_PCA_7       float32
V_pattern_1341337460919381558_PCA_8       float32
V_pattern_1341337460919381558_PCA_9       float32
V_pattern_1341337460919381558_PCA_10      float32
V_pattern_1341337460919381558_PCA_11      float32
V_pattern_1341337460919381558_PCA_12      float32
V_pattern_1341337460919381558_PCA_13      float32
V_pattern_1341337460919381558_PCA_14      float32
V_pattern_1341337460919381558_PCA_15      float32
V_pattern_2390559773846796271_PCA_1       float32
V_pattern_2390559773846796271_PCA_2       float32
V_pattern_2390559773846796271_PCA_3       float32
V_pattern_2390559773846796271_PCA_4       float32
V_pattern_2390559773846796271_PCA_5       float32
V_pattern_2390559773846796271_PCA_6       float32
V_pattern_2390559773846796271_PCA_7       float32
V_pattern_2390559773846796271_PCA_8       float32
V_pattern_2390559773846796271_PCA_9       float32
V_pattern_2390559773846796271_PCA_10      float32
V_pattern_2390559773846796271_PCA_11      float32
V_pattern_2390559773846796271_PCA_12      float32
V_pattern_2390559773846796271_PCA_13      float32
V_pattern_2390559773846796271_PCA_14      float32
V_pattern_2390559773846796271_PCA_15      float32
V_pattern_4432320641817836411_PCA_1       float32
V_pattern_4432320641817836411_PCA_2       float32
V_pattern_4432320641817836411_PCA_3       float32
V_pattern_4432320641817836411_PCA_4       float32
V_pattern_4432320641817836411_PCA_5       float32
V_pattern_4432320641817836411_PCA_6       float32
V_pattern_4432320641817836411_PCA_7       float32
V_pattern_4432320641817836411_PCA_8       float32
V_pattern_4432320641817836411_PCA_9       float32
V_pattern_4432320641817836411_PCA_10      float32
V_pattern_4432320641817836411_PCA_11      float32
V_pattern_4432320641817836411_PCA_12      float32
V_pattern_4432320641817836411_PCA_13      float32
V_pattern_4432320641817836411_PCA_14      float32
V_pattern_4432320641817836411_PCA_15      float32
V_pattern_6083775613017315007_PCA_1       float32
V_pattern_6083775613017315007_PCA_2       float32
V_pattern_6083775613017315007_PCA_3       float32
V_pattern_6083775613017315007_PCA_4       float32
V_pattern_6083775613017315007_PCA_5       float32
V_pattern_6083775613017315007_PCA_6       float32
V_pattern_6083775613017315007_PCA_7       float32
V_pattern_6083775613017315007_PCA_8       float32
V_pattern_6083775613017315007_PCA_9       float32
V_pattern_6083775613017315007_PCA_10      float32
V_pattern_6083775613017315007_PCA_11      float32
V_pattern_6517030450377495652_PCA_1       float32
V_pattern_6517030450377495652_PCA_2       float32
V_pattern_6517030450377495652_PCA_3       float32
V_pattern_6517030450377495652_PCA_4       float32
V_pattern_6517030450377495652_PCA_5       float32
V_pattern_6517030450377495652_PCA_6       float32
V_pattern_6517030450377495652_PCA_7       float32
V_pattern_6517030450377495652_PCA_8       float32
V_pattern_6517030450377495652_PCA_9       float32
V_pattern_6517030450377495652_PCA_10      float32
V_pattern_6517030450377495652_PCA_11      float32
V_pattern_6517030450377495652_PCA_12      float32
V_pattern_6517030450377495652_PCA_13      float32
V_pattern_6517030450377495652_PCA_14      float32
V_pattern_6517030450377495652_PCA_15      float32
V_pattern_7955208920290835429_PCA_1       float32
V_pattern_7955208920290835429_PCA_2       float32
V_pattern_7955208920290835429_PCA_3       float32
V_pattern_7955208920290835429_PCA_4       float32
V_pattern_7955208920290835429_PCA_5       float32
V_pattern_7955208920290835429_PCA_6       float32
V_pattern_7955208920290835429_PCA_7       float32
V_pattern_7955208920290835429_PCA_8       float32
V_pattern_7955208920290835429_PCA_9       float32
V_pattern_7955208920290835429_PCA_10      float32
V_pattern_7955208920290835429_PCA_11      float32
V_pattern_7955208920290835429_PCA_12      float32
V_pattern_7955208920290835429_PCA_13      float32
V_pattern_7955208920290835429_PCA_14      float32
V_pattern_7955208920290835429_PCA_15      float32
V_pattern_8258368889346774270_PCA_1       float32
V_pattern_8258368889346774270_PCA_2       float32
V_pattern_8258368889346774270_PCA_3       float32
V_pattern_8258368889346774270_PCA_4       float32
V_pattern_8258368889346774270_PCA_5       float32
V_pattern_8258368889346774270_PCA_6       float32
V_pattern_8258368889346774270_PCA_7       float32
V_pattern_8258368889346774270_PCA_8       float32
V_pattern_8258368889346774270_PCA_9       float32
V_pattern_8258368889346774270_PCA_10      float32
V_pattern_8258368889346774270_PCA_11      float32
V_pattern_8258368889346774270_PCA_12      float32
V_pattern_8258368889346774270_PCA_13      float32
V_pattern_8258368889346774270_PCA_14      float32
V_pattern_8258368889346774270_PCA_15      float32
id_01                                     float32
id_02                                     float32
id_03                                     float32
id_04                                     float32
id_05                                     float32
id_06                                     float32
id_09                                     float32
id_11                                     float32
id_12                                    category
id_13                                    category
id_14                                    category
id_15                                    category
id_16                                    category
id_18                                    category
id_19                                    category
id_20                                    category
id_21                                    category
id_28                                    category
id_29                                    category
id_30                                    category
id_31                                    category
id_32                                    category
id_35                                    category
id_36                                    category
id_37                                    category
id_38                                    category
DeviceType                               category
DeviceInfo                               category
screen_area                               float32
user_id_primary                               str
user_id_refined                               str
D4_N_user_id_refined_mean                 float32
D4_N_user_id_refined_std                  float32
D10_N_user_id_refined_mean                float32
D10_N_user_id_refined_std                 float32
D15_N_user_id_refined_mean                float32
D15_N_user_id_refined_std                 float32
D9_user_id_refined_mean                   float32
D9_user_id_refined_std                    float32
C1_user_id_refined_mean                   float32
C2_user_id_refined_mean                   float32
C5_user_id_refined_mean                   float32
C6_user_id_refined_mean                   float32
C7_user_id_refined_mean                   float32
C8_user_id_refined_mean                   float32
C9_user_id_refined_mean                   float32
C11_user_id_refined_mean                  float32
C12_user_id_refined_mean                  float32
C13_user_id_refined_mean                  float32
_num_M1_user_id_refined_mean              float32
_num_M5_user_id_refined_mean              float32
_num_M6_user_id_refined_mean              float32
_num_M8_user_id_refined_mean              float32
P_emaildomain_user_id_refined_nunique     float32
R_emaildomain_user_id_refined_nunique     float32
id_02_user_id_refined_nunique             float32
ProductCD_user_id_refined_nunique         float32
uid_stream_count                            int32
stream_tx_sequence_idx                      int32
user_amt_mean                             float32
user_amt_std                              float32
user_amt_min                              float32
user_amt_max                              float32
amt_dev_from_user_mean                    float32
amt_ratio_to_user_mean                    float32
time_since_last_tx                        float32
time_since_prev2_tx                       float32
time_since_last_same_amt                  float32
cum_count_same_amt                          int32
is_same_amt_as_prev                          int8
cum_historical_mean_amt                   float32
amt_dev_from_cum_mean                     float32
addr1_amt_dev_mean                        float32
addr1_amt_dev_median                      float32
addr1_amt_zscore                          float32
ProductCD_amt_dev_mean                    float32
ProductCD_amt_dev_median                  float32
ProductCD_amt_zscore                      float32
cum_unique_p_emails                         int16
cum_unique_devices                          int16
dtype: object